[tool.poetry]
name = "api"
version = "0.1.0"
description = ""
authors = ["Nikolas Schriefer <info@nikolasschriefer.de>"]

[tool.poetry.dependencies]
python = "^3.8"
flask = "^1.1.2"
zappa = "^0.51.0"
pandas = "^1.0.5"
joblib = "^0.16.0"
sklearn = "^0.0"

[tool.poetry.dev-dependencies]
python-dotenv = "^0.13.0"
flake8 = "^3.8.3"
coverage = "^5.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
